import {
  CustomerAddress,
  CustomerRecord,
  DashboardSnapshot,
  InventoryItem,
  OrderDetail,
  OrderRecord,
  SettingsRecord,
} from './types';
import { ORDER_STEP_SEQUENCE } from './constants';
import { formatISO } from 'date-fns';

const now = new Date();

export const demoOrders: OrderRecord[] = [
  {
    id: 'ord-001',
    customer_id: 'cus-001',
    customer_name: 'Constructora Atlas',
    status: 'en_route',
    priority: 'high',
    service_type: 'Emergencia',
    address_text: 'Av. Reforma 123, CDMX',
    geo_lat: 19.4326077,
    geo_lng: -99.133208,
    window_start: formatISO(now),
    total_final: 18500,
    labor_rate_per_hour: 850,
    labor_hours: 10,
    materials_subtotal: 4500,
    created_at: formatISO(now),
    updated_at: formatISO(now),
  },
  {
    id: 'ord-002',
    customer_id: 'cus-002',
    customer_name: 'Residencial Alameda',
    status: 'scheduled',
    priority: 'normal',
    service_type: 'Mantenimiento',
    address_text: 'Calle 5 #88, Naucalpan',
    geo_lat: 19.47435,
    geo_lng: -99.23751,
    window_start: formatISO(now),
    total_final: 7500,
    labor_rate_per_hour: 650,
    labor_hours: 6,
    materials_subtotal: 2000,
    created_at: formatISO(now),
  },
  {
    id: 'ord-003',
    customer_id: 'cus-003',
    customer_name: 'Fabricas Arali',
    status: 'job_done',
    priority: 'normal',
    service_type: 'Instalación',
    address_text: 'Parque Industrial 45, Toluca',
    geo_lat: 19.2837,
    geo_lng: -99.6557,
    window_start: formatISO(now),
    total_final: 32000,
    labor_rate_per_hour: 900,
    labor_hours: 18,
    materials_subtotal: 15000,
    created_at: formatISO(now),
  },
  {
    id: 'ord-004',
    customer_id: 'cus-004',
    customer_name: 'Hotel Aurora',
    status: 'paid',
    priority: 'emergency',
    service_type: 'Reparación',
    address_text: 'Zona Hotelera, Cancún',
    geo_lat: 21.133,
    geo_lng: -86.743,
    window_start: formatISO(now),
    total_final: 56000,
    labor_rate_per_hour: 1200,
    labor_hours: 20,
    materials_subtotal: 25000,
    created_at: formatISO(now),
  },
  {
    id: 'ord-005',
    customer_id: 'cus-005',
    customer_name: 'Colegio Faro',
    status: 'draft',
    priority: 'low',
    service_type: 'Inspección',
    address_text: 'Av. Universidad 2000, Querétaro',
    geo_lat: 20.5888,
    geo_lng: -100.3899,
    window_start: formatISO(now),
    total_final: 2800,
    labor_rate_per_hour: 600,
    labor_hours: 3,
    materials_subtotal: 400,
    created_at: formatISO(now),
  },
];

export const demoCustomers: CustomerRecord[] = [
  {
    id: 'cus-001',
    name: 'Constructora Atlas',
    phone: '+52 55 6789 4321',
    email: 'contacto@atlas.mx',
    address_text: 'Av. Reforma 123, CDMX',
    tags: ['B2B', 'VIP'],
    created_at: formatISO(now),
  },
  {
    id: 'cus-002',
    name: 'Residencial Alameda',
    phone: '+52 55 1357 2468',
    email: 'admin@alameda.mx',
    address_text: 'Calle 5 #88, Naucalpan',
    tags: ['Residencial'],
    created_at: formatISO(now),
  },
  {
    id: 'cus-003',
    name: 'Fabricas Arali',
    phone: '+52 722 555 9988',
    email: 'mantenimiento@arali.mx',
    address_text: 'Parque Industrial 45, Toluca',
    tags: ['Industrial'],
    created_at: formatISO(now),
  },
  {
    id: 'cus-004',
    name: 'Hotel Aurora',
    phone: '+52 998 222 4411',
    email: 'ops@aurora.mx',
    address_text: 'Zona Hotelera, Cancún',
    tags: ['Hotel'],
    created_at: formatISO(now),
  },
  {
    id: 'cus-005',
    name: 'Colegio Faro',
    phone: '+52 442 777 8899',
    email: 'compras@faro.mx',
    address_text: 'Av. Universidad 2000, Querétaro',
    tags: ['Educación'],
    created_at: formatISO(now),
  },
];

export const demoCustomerAddresses: CustomerAddress[] = [
  {
    id: 'addr-1',
    customer_id: 'cus-001',
    label: 'Obra Centro',
    address: 'Av. Reforma 123, CDMX',
    lat: 19.4326077,
    lng: -99.133208,
  },
  {
    id: 'addr-2',
    customer_id: 'cus-002',
    label: 'Condominio 1',
    address: 'Calle 5 #88, Naucalpan',
    lat: 19.47435,
    lng: -99.23751,
  },
];

export const demoInventory: InventoryItem[] = [
  {
    id: 'inv-001',
    truck_id: 'truck-1',
    truck_name: 'Truck Norte',
    item_name: 'Tubo PVC 1/2',
    qty_on_hand: 12,
    min_threshold: 8,
    updated_at: formatISO(now),
  },
  {
    id: 'inv-002',
    truck_id: 'truck-1',
    truck_name: 'Truck Norte',
    item_name: 'Coples 3/4',
    qty_on_hand: 4,
    min_threshold: 10,
    updated_at: formatISO(now),
  },
  {
    id: 'inv-003',
    truck_id: 'truck-2',
    truck_name: 'Truck Centro',
    item_name: 'Gas LP manguera',
    qty_on_hand: 2,
    min_threshold: 6,
    updated_at: formatISO(now),
  },
];

export const demoSettings: SettingsRecord = {
  id: 'tenant',
  company_name: 'Opsis Plumbing',
  phone: '+52 55 1234 5678',
  email: 'contacto@opsis.mx',
  address: 'CDMX, México',
  theme: 'light',
  palette: 'default',
  customRates: [
    { id: 'rate-1', concept: 'Mano de obra por hora', type: 'hourly', price: 850 },
    { id: 'rate-2', concept: 'Emergencia nocturna', type: 'emergency', price: 2500 },
  ],
};

export const demoDashboardSnapshot: DashboardSnapshot = {
  stats: {
    pending: 4,
    inProgress: 2,
    completedToday: 3,
    revenueToday: 86450,
    criticalMaterials: 2,
  },
  recentOrders: demoOrders.slice(0, 4),
  mapJobs: demoOrders
    .filter((order) => order.geo_lat && order.geo_lng)
    .map((order) => ({
      id: order.id,
      lat: order.geo_lat!,
      lng: order.geo_lng!,
      status: order.status,
      address: order.address_text || 'Sin dirección',
      service_type: order.service_type,
      priority: order.priority,
    })),
};

export const demoOrderDetail: OrderDetail = {
  ...demoOrders[0],
  customer: demoCustomers[0],
  addresses: demoCustomerAddresses.filter((addr) => addr.customer_id === demoOrders[0].customer_id),
  materials: [
    {
      id: 'mat-1',
      order_id: 'ord-001',
      item_name: 'Bomba presurizadora 1HP',
      qty_used: 1,
      unit_cost: 3800,
      source_location: 'warehouse',
      created_at: formatISO(now),
    },
    {
      id: 'mat-2',
      order_id: 'ord-001',
      item_name: 'Coples cobre',
      qty_used: 12,
      unit_cost: 85,
      source_location: 'truck',
      created_at: formatISO(now),
    },
  ],
  photos: [
    {
      id: 'pho-1',
      order_id: 'ord-001',
      url: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?auto=format&fit=crop&w=800&q=60',
      kind: 'before',
      caption: 'Equipo existente',
      created_at: formatISO(now),
    },
    {
      id: 'pho-2',
      order_id: 'ord-001',
      url: 'https://images.unsplash.com/photo-1581578017423-3fe03f41711c?auto=format&fit=crop&w=800&q=60',
      kind: 'after',
      caption: 'Instalación nueva',
      created_at: formatISO(now),
    },
  ],
  timeline: ORDER_STEP_SEQUENCE.map((status, idx) => ({
    id: `tl-${idx}`,
    label: status,
    status,
    timestamp: formatISO(new Date(now.getTime() - (idx + 1) * 60 * 60 * 1000)),
    description: `La orden avanzó al estado ${status}.`,
  })),
};
